# -*- coding: utf-8 -*-
"""pattern assin.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PoGF7W5Z0R2bkG8OImQNvxhTHoTBLo75
"""

#patterns
for i in range(1,5):
  for k in range(i):
    print(" ",end=" ")
  for j in range(1,5):
    print("*" , end=" ")
  print()

for i in range(1,5):
  for j in range(1,7):
    if (i==1 or i==4 or j==1 or j==6):
      print("*",end=" ")
    else:
      print(" ",end=" ")
  print()

n=6
for i in range(1,n):
  num=65
  for j in range(i):
    print(chr(num),end=" ")
    num+=1
  print()

n=6
num=65
for i in range(1,n):
  for j in range(1,i+1):
    print(chr(num),end=" ")
  num+=1
  print()

n=5
for i in range(n):
  for j in range(n-i-1,n):
    print(chr(65+j),end=" ")
  print()

n=4
for i in range(1,n+1):
  for k in range(i,n):
    print(" ",end=" ")
  for j in range(1,2*i):
    print("*",end=" ")
  print()

n=4
for i in range(n):
  for k in range(n-i):
    print(" ",end=" ")
  for j in range(2*i+1):
    if j==0 or j==2*i or i==n-1:
      print("*",end=" ")
    else:
      print(" ",end=" ")
  print()

n=4
for i in range(n):
  for k in range(i):
    print(" ",end="")
  for j in range(2*(n-i)-1):
    print("*",end=" ")
  print()

for i in range(1,5):
  for j in range(1,i+1):
    print("*",end=" ")
  print()
for i in range(1,4):
  for j in range(i,4):
    print("*",end=" ")
  print()

n=5
for i in range(n):
  for k in range(i,n):
    print(" ",end="")
  for j in range(i+1):
    print("*",end="")
  print()

n=5
for i in range(n):
  num=1
  for k in range(i,n):
    print(" ",end="")
  for j in range(i+1):
    print(num,end="")
    num+=1
  print()

n=5
for i in range(n):
  for k in range(i,n):
    print(" ",end="")
  for j in range(i+1):
    print("*",end="")
  print()
n=5
for i in range(n):
  for k in range(i+1):
    print(" ",end="")
  for j in range(i,n):
    print("*",end="")
  print()

n=5
for i in range(n):
  num=1
  for k in range(i+1):
    print(" ",end=" ")
  for j in range(i,n):
    print(num,end=" ")
    num+=1
  print()

n = 5
for i in range(n):
    num = 65
    for k in range(i):
        print(" ", end=" ")
    for j in range(i, n):
        print(chr(num), end=" ")
        num += 1
    print()

for i in range(1,6):
  for k in range(i,n):
    print(" ",end=" ")
  for j in range(1,6):
    print("*" , end=" ")
  print()

for i in range(1,6):
  num=1
  for k in range(i,n):
    print(" ",end=" ")
  for j in range(1,6):
    print(num , end=" ")
    num+=1
  print()

for i in range(1,6):
  num=65
  for k in range(i,n):
    print(" ",end=" ")
  for j in range(1,6):
    print(chr(num) , end=" ")
    num+=1
  print()